
---
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'debian/**'
      - 'doc/**'
      - 'subprojects/**'
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'debian/**'
      - 'doc/**'
      - 'subprojects/**'
    branches:
      - master

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - id: checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            meson \
            ccache \
            libavahi-client-dev \
            libgeoip-dev \
            libgtest-dev \
            libsystemd-dev \
            libz-dev

      - id: cache-ccache
        uses: hendrikmuhs/ccache-action@v1

      - name: Configure
        run: |
          meson setup \
            -Ddocumentation=disabled \
            -Dsystemd=enabled \
            -Dgeoip=enabled \
            -Dzeroconf=enabled \
            --force-fallback-for=fmt \
            output

      - name: Build
        run: ninja -C output -v

      - name: Unit Tests
        run: meson test -C output

      - name: Dump Unit Test Log
        if: ${{ failure() }}
        continue-on-error: true
        run: cat output/meson-logs/testlog.txt
