
---
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'debian/**'
      - 'doc/**'
      - 'subprojects/**'
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'debian/**'
      - 'doc/**'
      - 'subprojects/**'
    branches:
      - master

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - id: cache-ccache
        uses: hendrikmuhs/ccache-action@v1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libavahi-client-dev \
            libboost-dev \
            libfmt-dev \
            libgeoip-dev \
            libgtest-dev \
            libsystemd-dev \
            libz-dev

      - name: Build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          setup-options: -Ddocumentation=disabled
          meson-version: 0.56.0

      - name: Unit Tests
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          setup-options: -Ddocumentation=disabled
          meson-version: 0.56.0
